---
deployment:
  tasks:
    - export DEPLOYPATH=/home/holycow/public_html/workshop/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp config.js $DEPLOYPATH
    - /bin/cp -R assets/. $DEPLOYPATH/assets/
